### ISSUE TITLE
请问您这个支持字符串格式化吗？

### ISSUE THREAD

**Issue by xxjwxc** [fsgo/go_fmt#1]
比如我传入一个非格式化的struct 字符串：

type Test struct{aa int;bb string}

能够格式化出来吗？

**Comment by hidu** [comment]
你说的是调用内部API来格式化字符串吗？目前还没有暴露api出来。

**Comment by xxjwxc** [comment]
是的：我觉得暴露api比较好。至少相对于gofmt,goimports 就有优势了。不然跟这两个工具差不多功能。不能体现出优势

**Comment by xxjwxc** [comment]
感谢你的回答。
